// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:moody/features/home/data/models/activity_entry_model.dart';
import 'package:moody/features/home/data/models/mood_entry_model.dart';
import 'package:moody/features/settings/data/models/user_settings_model.dart';
import 'package:moody/features/wellness/data/models/gratitude_entry_model.dart';
import 'package:moody/features/wellness/data/models/quote_model.dart';
import 'package:moody/features/wellness/data/models/sound_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityEntryModelAdapter());
    registerAdapter(GratitudeEntryModelAdapter());
    registerAdapter(MoodEntryModelAdapter());
    registerAdapter(QuoteModelAdapter());
    registerAdapter(SoundModelAdapter());
    registerAdapter(UserSettingsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActivityEntryModelAdapter());
    registerAdapter(GratitudeEntryModelAdapter());
    registerAdapter(MoodEntryModelAdapter());
    registerAdapter(QuoteModelAdapter());
    registerAdapter(SoundModelAdapter());
    registerAdapter(UserSettingsModelAdapter());
  }
}
